from setuptools import setup, find_packages

setup(
    name='PAlign',
    version='0.1.0',
    description='Personalized Alignment with PASO for Large Language Models',
    author='xxx',
    author_email='xxx',
    url='xxx',
    packages=find_packages(),
    install_requires=[
        'accelerate==1.12.0',
        'baukit @ git+https://github.com/davidbau/baukit.git@9d51abd51ebf29769aecc38c4cbef459b731a36e',
        'datasets==4.5.0',
        'einops==0.8.2',
        'huggingface_hub==0.36.2',
        'matplotlib==3.10.8',
        'numpy==2.3.5',
        'openpyxl==3.1.5',
        'pandas==3.0.1',
        'requests==2.32.5',
        'safetensors==0.7.0',
        'scikit-learn==1.8.0',
        'torch==2.5.1',
        'torchvision==0.20.1',
        'tqdm==4.67.3',
        'transformers==4.57.6',
        'xlrd==2.0.2',
    ],
    classifiers=[
        'Programming Language :: Python :: 3',
        'License :: OSI Approved :: MIT License',
        'Operating System :: OS Independent',
    ],
    python_requires='>=3.11',
)
